// Merges the lamp crop rectangles written by extract_lamps.ps1 into game/lampdata.js
const fs = require("fs");
const path = require("path");
const dir = path.join(__dirname, "..", "game", "assets", "lamps");
// only the first round lamp was lit on the photo; the five share the same artwork
for (let i = 2; i <= 5; i++) fs.copyFileSync(path.join(dir, "rc1.png"), path.join(dir, `rc${i}.png`));
const read = (f) => JSON.parse(fs.readFileSync(path.join(dir, f), "utf8").replace(/^﻿/, ""));
const data = { top: read("_top.json"), reel: read("_reel.json") };
const out = path.join(__dirname, "..", "game", "lampdata.js");
fs.writeFileSync(out, "// generated by tools/make_lampdata.js — lamp layer id -> [x, y, w, h] in texture pixels\n" +
  "(function (root) { (root.CBJ = root.CBJ || {}).lampRects = " + JSON.stringify(data) + "; })(typeof window !== \"undefined\" ? window : globalThis);\n");
console.log(`lampdata: ${Object.keys(data.top).length} top + ${Object.keys(data.reel).length} reel -> ${out}`);
